# Imports

In [1]:
from pathlib import Path
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet
from datetime import datetime

# Load main data

In [2]:
SOURCEDIR = r"../40_FLUX_PROCESSING_CHAIN"
FILENAME = r"46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
maindf = load_parquet(filepath=FILEPATH)
maindf

Loaded .parquet file ..\40_FLUX_PROCESSING_CHAIN\46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4.parquet (0.942 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SCH4_SINGLE_gfRMED_L3.1_ISFILLED  FCH4_L3.1  FCH4_L3.1_QCF  FCH4_L3.1_QCF0  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HAMPEL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_FCH4_L3.1_HARDFLAGS  SUM_L3.2_FCH4_L3.1_SOFTFLAGS  SUM_L3.2_FCH4_L3.1_FLAGS  FLAG_L3.2_FCH4_L3.1_QCF  FCH4_L3.1_L3.2_QCF  FCH4_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    1.0 -18.790539            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0  -4.360399      -4.360399             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           -4.360399                  NaN
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   6.843150            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   2.488800       2.488800        2.488800                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            2.488800             2.488800
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0  -9.177059      -9.177059       -9.177059                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0           -9.177059            -9.177059
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                    ...        ...            ...             ...                                          ...                                     ...                                          ...                                          ...                                                ...                            ...                           ...                       ...                      ...                 ...                  ...
2024-08-22 21:45:00  1014.14      1.14108  0.025231     1157.22         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0 -14.386380     -14.386380             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0          -14.386380                  NaN
2024-08-22 22:15:00  1014.10      1.14388  0.025170     1160.01         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  49.838100      49.838100             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           49.838100                  NaN
2024-08-22 22:45:00  1014.08      1.14405  0.025167     1160.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  14.259800            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2024-08-22 23:15:00  1014.01      1.14569  0.025132     1161.74         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  14.943390      14.943390             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           14.943390                  NaN
2024-08-22 23:45:00  1014.01      1.14436  0.025161     1160.39         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   5.248787            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN

[13889 rows x 567 columns]

# Load REddyProc output

In [3]:
SOURCEDIR = r"../50_REDDYPROC"
FILENAME = r"51.1_UstarThresholds_MDS-gapfilled_NEE-partitioned.csv"
FILEPATH = Path(SOURCEDIR) / FILENAME
reddy = pd.read_csv(FILEPATH)

# Convert timestamp to datetime and change from end to middle
reddy['TIMESTAMP_MIDDLE'] = pd.to_datetime(reddy['TIMESTAMP_END'], format='%Y-%m-%dT%H:%M:%SZ', errors='coerce') - pd.Timedelta(minutes=15)
# Drop the timestamp end
reddy.drop(columns='TIMESTAMP_END', inplace=True)
# Set the timestamp as index
reddy.set_index('TIMESTAMP_MIDDLE', inplace=True)

# Add a string to identify the reddyproc columns later
reddy.columns = [f'{c}_reddyproc' for c in reddy.columns]

reddy

                     Ustar_U16_Thres_reddyproc  Ustar_U50_Thres_reddyproc  Ustar_U84_Thres_reddyproc  NEE_U16_f_reddyproc  NEE_U50_f_reddyproc  NEE_U84_f_reddyproc  GPP_U16_f_reddyproc  GPP_U50_f_reddyproc  GPP_U84_f_reddyproc  Reco_U16_reddyproc  Reco_U50_reddyproc  Reco_U84_reddyproc  LE_f_reddyproc  H_f_reddyproc
TIMESTAMP_MIDDLE
2023-10-16 23:15:00                   0.084582                   0.109093                   0.134977             1.459812             1.461735             1.489906             0.108129             0.127796             0.156144            1.567941            1.589532            1.646051        5.547594     -10.692948
2023-10-16 23:45:00                   0.084582                   0.109093                   0.134977             1.450082             1.451357             1.478488             0.117859             0.138175             0.167562            1.567941            1.589532            1.646051        5.547594     -10.692948
2023-10-17 00:15:00                   0.084582                   0.109093                   0.134977             1.432370             1.432507             1.450670             0.077955             0.099241             0.136408            1.510325            1.531747            1.587078        5.556566      -9.246736
2023-10-17 00:45:00                   0.084582                   0.109093                   0.134977             1.424641             1.424261             1.441940             0.043256             0.064918             0.101674            1.467896            1.489179            1.543615        5.537643     -10.266117
2023-10-17 01:15:00                   0.084582                   0.109093                   0.134977             1.428483             1.428362             1.445870             0.058188             0.079654             0.116980            1.486671            1.508017            1.562851        5.556566      -9.246736
...                                        ...                        ...                        ...                  ...                  ...                  ...                  ...                  ...                  ...                 ...                 ...                 ...             ...            ...
2024-08-22 20:45:00                   0.089121                   0.109520                   0.134977             4.517046             4.611143             4.497522            -0.336488            -0.389342            -0.221623            4.180558            4.221801            4.275899        4.908718      -7.224344
2024-08-22 21:15:00                   0.089121                   0.109520                   0.134977             4.545872             4.603141             4.473330            -0.529545            -0.545419            -0.361207            4.016327            4.057722            4.112123        4.951884      -5.818081
2024-08-22 21:45:00                   0.089121                   0.109520                   0.134977             4.545872             4.603141             4.473330            -0.543295            -0.559160            -0.374926            4.002577            4.043981            4.098404        4.951884      -5.818081
2024-08-22 22:15:00                   0.089121                   0.109520                   0.134977             4.394256             4.437373             4.399418            -0.486607            -0.488269            -0.395766            3.907649            3.949104            4.003652        3.541709      -5.297809
2024-08-22 22:45:00                   0.089121                   0.109520                   0.134977             4.523599             4.580435             4.473330            -0.545417            -0.560833            -0.399270            3.978182            4.019602            4.074060        4.850506      -5.818081

[14928 rows x 14 columns]

# Merge

In [4]:
newcols = [c for c in reddy.columns if c not in maindf]
print("NEW VARIABLES FROM REDDYPROC:")
[print(f"+ {c}") for c in newcols]
maindf = pd.concat([maindf, reddy[newcols]], axis=1)
maindf

NEW VARIABLES FROM REDDYPROC:
+ Ustar_U16_Thres_reddyproc
+ Ustar_U50_Thres_reddyproc
+ Ustar_U84_Thres_reddyproc
+ NEE_U16_f_reddyproc
+ NEE_U50_f_reddyproc
+ NEE_U84_f_reddyproc
+ GPP_U16_f_reddyproc
+ GPP_U50_f_reddyproc
+ GPP_U84_f_reddyproc
+ Reco_U16_reddyproc
+ Reco_U50_reddyproc
+ Reco_U84_reddyproc
+ LE_f_reddyproc
+ H_f_reddyproc

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FCH4_L3.1_L3.2_QCF0  Ustar_U16_Thres_reddyproc  Ustar_U50_Thres_reddyproc  Ustar_U84_Thres_reddyproc  NEE_U16_f_reddyproc  NEE_U50_f_reddyproc  NEE_U84_f_reddyproc  GPP_U16_f_reddyproc  GPP_U50_f_reddyproc  GPP_U84_f_reddyproc  Reco_U16_reddyproc  Reco_U50_reddyproc  Reco_U84_reddyproc  LE_f_reddyproc  H_f_reddyproc
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-10-16 23:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                  NaN                   0.084582                   0.109093                   0.134977             1.459812             1.461735             1.489906             0.108129             0.127796             0.156144            1.567941            1.589532            1.646051        5.547594     -10.692948
2023-10-16 23:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                  NaN                   0.084582                   0.109093                   0.134977             1.450082             1.451357             1.478488             0.117859             0.138175             0.167562            1.567941            1.589532            1.646051        5.547594     -10.692948
2023-10-17 00:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                  NaN                   0.084582                   0.109093                   0.134977             1.432370             1.432507             1.450670             0.077955             0.099241             0.136408            1.510325            1.531747            1.587078        5.556566      -9.246736
2023-10-17 00:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                  NaN                   0.084582                   0.109093                   0.134977             1.424641             1.424261             1.441940             0.043256             0.064918             0.101674            1.467896            1.489179            1.543615        5.537643     -10.266117
2023-10-17 01:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                  NaN                   0.084582                   0.109093                   0.134977             1.428483             1.428362             1.445870             0.058188             0.079654             0.116980            1.486671            1.508017            1.562851        5.556566      -9.246736
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                  ...                        ...                        ...                        ...                  ...                  ...                  ...                  ...                  ...                  ...                 ...                 ...                 ...             ...            ...
2024-08-22 21:45:00  1014.14      1.14108  0.025231     1157.22         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                  NaN                   0.089121                   0.109520                   0.134977             4.545872             4.603141             4.473330            -0.543295            -0.559160            -0.374926            4.002577            4.043981            4.098404        4.951884      -5.818081
2024-08-22 22:15:00  1014.10      1.14388  0.025170     1160.01         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                  NaN                   0.089121                   0.109520                   0.134977             4.394256             4.437373             4.399418            -0.486607            -0.488269            -0.395766            3.907649            3.949104            4.003652        3.541709      -5.297809
2024-08-22 22:45:00  1014.08      1.14405  0.025167     1160.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                  NaN                   0.089121                   0.109520                   0.134977             4.523599             4.580435             4.473330            -0.545417            -0.560833            -0.399270            3.978182            4.019602            4.074060        4.850506      -5.818081
2024-08-22 23:15:00  1014.01      1.14569  0.025132     1161.74         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                  NaN                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN
2024-08-22 23:45:00  1014.01      1.14436  0.025161     1160.39         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                  NaN                        NaN                        NaN                        NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                 NaN                 NaN             NaN            NaN

[14930 rows x 581 columns]

# Export

In [5]:
filename = "61.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4_REDDYPROC"
save_parquet(data=maindf, filename=filename)

Saved file 61.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4_REDDYPROC.parquet (1.833 seconds).

'61.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4_REDDYPROC.parquet'

# End of notebook

In [6]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2026-09-17 16:27:38