# Imports

In [1]:
from pathlib import Path
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet

# Load L3.3 results for NEE, LE and H

In [2]:
nee = load_parquet(filepath=r"41_NEE/41.1_FluxProcessingChain_L3.2_NEE.parquet")
le = load_parquet(filepath=r"42_LE/42.1_FluxProcessingChain_L3.2_LE.parquet")
h = load_parquet(filepath=r"43_H/43.1_FluxProcessingChain_L3.2_H.parquet")
n2o = load_parquet(filepath=r"44_FN2O/44.1_FluxProcessingChain_L3.2_FN2O.parquet")
ch4 = load_parquet(filepath=r"45_FCH4/45.1_FluxProcessingChain_L3.2_FCH4.parquet")

Loaded .parquet file 41_NEE/41.1_FluxProcessingChain_L3.2_NEE.parquet (0.389 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file 42_LE/42.1_FluxProcessingChain_L3.2_LE.parquet (0.313 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file 43_H/43.1_FluxProcessingChain_L3.2_H.parquet (0.259 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file 44_FN2O/44.1_FluxProcessingChain_L3.2_FN2O.parquet (0.330 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file 45_FCH4/45.1_FluxProcessingChain_L3.2_FCH4.parquet (0.281 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

In [3]:
# Load METEO
SOURCEDIR = r"../10_METEO"
FILENAME = r"13.1_CH-TAN_meteo_gapfilled.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
meteo = load_parquet(filepath=FILEPATH)

Loaded .parquet file ..\10_METEO\13.1_CH-TAN_meteo_gapfilled.parquet (0.133 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

# Load main data

In [4]:
SOURCEDIR = r"../30_MERGE_DATA"
FILENAME = r"33.1_CH-TAN_IRGA+LGR_Level-1_eddypro_fluxnet.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
maindf = load_parquet(filepath=FILEPATH)

Loaded .parquet file ..\30_MERGE_DATA\33.1_CH-TAN_IRGA+LGR_Level-1_eddypro_fluxnet.parquet (0.249 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

## Add results for NEE

In [5]:
newcols = [c for c in nee.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, nee[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ DAYTIME
++ NIGHTTIME
++ FLAG_L2_FC_MISSING_TEST
++ FLAG_L2_FC_SSITC_TEST
++ FLAG_L2_FC_COMPLETENESS_TEST
++ FLAG_L2_FC_SCF_TEST
++ FLAG_L2_FC_SIGNAL_STRENGTH_TEST
++ FLAG_L2_FC_CO2_VM97_SPIKE_HF_TEST
++ FLAG_L2_FC_CO2_VM97_DROPOUT_TEST
++ SUM_L2_FC_HARDFLAGS
++ SUM_L2_FC_SOFTFLAGS
++ SUM_L2_FC_FLAGS
++ FLAG_L2_FC_QCF
++ FC_L2_QCF
++ FC_L2_QCF0
++ SC_SINGLE_gfRMED_L3.1
++ FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED
++ NEE_L3.1
++ NEE_L3.1_QCF
++ NEE_L3.1_QCF0
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST
++ SUM_L3.2_NEE_L3.1_HARDFLAGS
++ SUM_L3.2_NEE_L3.1_SOFTFLAGS
++ SUM_L3.2_NEE_L3.1_FLAGS
++ FLAG_L3.2_NEE_L3.1_QCF
++ NEE_L3.1_L3.2_QCF
++ NEE_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  SC_SINGLE_gfRMED_L3.1  FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED  NEE_L3.1  NEE_L3.1_QCF  NEE_L3.1_QCF0  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST  SUM_L3.2_NEE_L3.1_HARDFLAGS  SUM_L3.2_NEE_L3.1_SOFTFLAGS  SUM_L3.2_NEE_L3.1_FLAGS  FLAG_L3.2_NEE_L3.1_QCF  NEE_L3.1_L3.2_QCF  NEE_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                    NaN                                  NaN       NaN           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                    ...                                  ...       ...           ...            ...                                         ...                                    ...                                         ...                                             ...                          ...                          ...                      ...                     ...                ...                 ...
2024-08-22 21:45:00  1014.14      1.14108  0.025231     1157.22         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               1.074240                                  0.0  0.656649           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2024-08-22 22:15:00  1014.10      1.14388  0.025170     1160.01         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               0.946812                                  0.0  8.221252           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          0.0                          1.0                      1.0                     2.0                NaN                 NaN
2024-08-22 22:45:00  1014.08      1.14405  0.025167     1160.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...              -0.752376                                  0.0  6.516684           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          0.0                          1.0                      1.0                     2.0                NaN                 NaN
2024-08-22 23:15:00  1014.01      1.14569  0.025132     1161.74         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               0.059655                                  0.0  8.987805           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          0.0                          1.0                      1.0                     2.0                NaN                 NaN
2024-08-22 23:45:00  1014.01      1.14436  0.025161     1160.39         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...              -0.613893                                  0.0  2.120787           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          0.0                          1.0                      1.0                     2.0                NaN                 NaN

[13889 rows x 455 columns]

## Add results for LE

In [6]:
newcols = [c for c in le.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, le[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_LE_MISSING_TEST
++ FLAG_L2_LE_SSITC_TEST
++ FLAG_L2_LE_COMPLETENESS_TEST
++ FLAG_L2_LE_SCF_TEST
++ FLAG_L2_LE_SIGNAL_STRENGTH_TEST
++ FLAG_L2_LE_H2O_VM97_SPIKE_HF_TEST
++ FLAG_L2_LE_H2O_VM97_DROPOUT_TEST
++ SUM_L2_LE_HARDFLAGS
++ SUM_L2_LE_SOFTFLAGS
++ SUM_L2_LE_FLAGS
++ FLAG_L2_LE_QCF
++ LE_L2_QCF
++ LE_L2_QCF0
++ SLE_SINGLE_gfRMED_L3.1
++ FLAG_SLE_SINGLE_gfRMED_L3.1_ISFILLED
++ LE_L3.1
++ LE_L3.1_QCF
++ LE_L3.1_QCF0
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL_TEST
++ SUM_L3.2_LE_L3.1_HARDFLAGS
++ SUM_L3.2_LE_L3.1_SOFTFLAGS
++ SUM_L3.2_LE_L3.1_FLAGS
++ FLAG_L3.2_LE_L3.1_QCF
++ LE_L3.1_L3.2_QCF
++ LE_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  LE_L2_QCF0  SLE_SINGLE_gfRMED_L3.1  FLAG_SLE_SINGLE_gfRMED_L3.1_ISFILLED   LE_L3.1  LE_L3.1_QCF  LE_L3.1_QCF0  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL_TEST  SUM_L3.2_LE_L3.1_HARDFLAGS  SUM_L3.2_LE_L3.1_SOFTFLAGS  SUM_L3.2_LE_L3.1_FLAGS  FLAG_L3.2_LE_L3.1_QCF  LE_L3.1_L3.2_QCF  LE_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...         NaN                     NaN                                   NaN       NaN          NaN           NaN                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...         NaN                     NaN                                   NaN       NaN          NaN           NaN                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...         NaN                     NaN                                   NaN       NaN          NaN           NaN                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...         NaN                     NaN                                   NaN       NaN          NaN           NaN                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...         NaN                     NaN                                   NaN       NaN          NaN           NaN                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...         ...                     ...                                   ...       ...          ...           ...                                        ...                                   ...                                        ...                         ...                         ...                     ...                    ...               ...                ...
2024-08-22 21:45:00  1014.14      1.14108  0.025231     1157.22         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN                0.117337                                   0.0 -0.555963          NaN           NaN                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
2024-08-22 22:15:00  1014.10      1.14388  0.025170     1160.01         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN               -0.114854                                   0.0 -4.093194          NaN           NaN                                        0.0                                 False                                        0.0                         0.0                         1.0                     1.0                    2.0               NaN                NaN
2024-08-22 22:45:00  1014.08      1.14405  0.025167     1160.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN               -0.094836                                   0.0 -2.782716          NaN           NaN                                        0.0                                 False                                        0.0                         0.0                         1.0                     1.0                    2.0               NaN                NaN
2024-08-22 23:15:00  1014.01      1.14569  0.025132     1161.74         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN               -0.213563                                   0.0 -1.691313          NaN           NaN                                        0.0                                 False                                        0.0                         2.0                         0.0                     2.0                    2.0               NaN                NaN
2024-08-22 23:45:00  1014.01      1.14436  0.025161     1160.39         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN                0.007007                                   0.0 -2.076323          NaN           NaN                                        0.0                                 False                                        0.0                         0.0                         1.0                     1.0                    2.0               NaN                NaN

[13889 rows x 482 columns]

## Add results for H

In [7]:
newcols = [c for c in h.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, h[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_H_MISSING_TEST
++ FLAG_L2_H_SSITC_TEST
++ FLAG_L2_H_COMPLETENESS_TEST
++ FLAG_L2_H_SCF_TEST
++ FLAG_L2_H_T_SONIC_VM97_SPIKE_HF_TEST
++ FLAG_L2_H_T_SONIC_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_H_T_SONIC_VM97_DROPOUT_TEST
++ SUM_L2_H_HARDFLAGS
++ SUM_L2_H_SOFTFLAGS
++ SUM_L2_H_FLAGS
++ FLAG_L2_H_QCF
++ H_L2_QCF
++ H_L2_QCF0
++ SH_SINGLE_gfRMED_L3.1
++ FLAG_SH_SINGLE_gfRMED_L3.1_ISFILLED
++ H_L3.1
++ H_L3.1_QCF
++ H_L3.1_QCF0
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL_TEST
++ SUM_L3.2_H_L3.1_HARDFLAGS
++ SUM_L3.2_H_L3.1_SOFTFLAGS
++ SUM_L3.2_H_L3.1_FLAGS
++ FLAG_L3.2_H_L3.1_QCF
++ H_L3.1_L3.2_QCF
++ H_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  H_L2_QCF0  SH_SINGLE_gfRMED_L3.1  FLAG_SH_SINGLE_gfRMED_L3.1_ISFILLED     H_L3.1  H_L3.1_QCF  H_L3.1_QCF0  FLAG_L3.2_H_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL_TEST  SUM_L3.2_H_L3.1_HARDFLAGS  SUM_L3.2_H_L3.1_SOFTFLAGS  SUM_L3.2_H_L3.1_FLAGS  FLAG_L3.2_H_L3.1_QCF  H_L3.1_L3.2_QCF  H_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...        NaN              -0.179467                                  1.0  -0.352882         NaN          NaN                                       0.0                                False                                       0.0                        6.0                        0.0                    6.0                   2.0              NaN               NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...        NaN              -0.089664                                  0.0  -5.434164         NaN          NaN                                       0.0                                False                                       0.0                        2.0                        0.0                    2.0                   2.0              NaN               NaN
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...        NaN              -0.179467                                  0.0  -1.975767   -1.975767          NaN                                       0.0                                False                                       0.0                        0.0                        1.0                    1.0                   1.0        -1.975767               NaN
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...   -10.9194              -0.764389                                  0.0 -11.683789  -11.683789   -11.683789                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -11.683789        -11.683789
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...   -10.8741               0.044976                                  0.0 -10.829124  -10.829124   -10.829124                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -10.829124        -10.829124
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...        ...                    ...                                  ...        ...         ...          ...                                       ...                                  ...                                       ...                        ...                        ...                    ...                   ...              ...               ...
2024-08-22 21:45:00  1014.14      1.14108  0.025231     1157.22         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...        NaN              -0.656896                                  0.0  -2.531776         NaN          NaN                                       0.0                                False                                       0.0                        0.0                        1.0                    1.0                   2.0              NaN               NaN
2024-08-22 22:15:00  1014.10      1.14388  0.025170     1160.01         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...        NaN              -0.928850                                  0.0 -13.215250         NaN          NaN                                       0.0                                False                                       0.0                        0.0                        1.0                    1.0                   2.0              NaN               NaN
2024-08-22 22:45:00  1014.08      1.14405  0.025167     1160.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...        NaN              -0.078504                                  0.0 -16.032504         NaN          NaN                                       0.0                                False                                       0.0                        0.0                        1.0                    1.0                   2.0              NaN               NaN
2024-08-22 23:15:00  1014.01      1.14569  0.025132     1161.74         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...        NaN              -0.545908                                  0.0 -11.038708         NaN          NaN                                       0.0                                False                                       0.0                        0.0                        1.0                    1.0                   2.0              NaN               NaN
2024-08-22 23:45:00  1014.01      1.14436  0.025161     1160.39         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...        NaN               0.405687                                  0.0  -4.885403         NaN          NaN                                       0.0                                False                                       0.0                        0.0                        1.0                    1.0                   2.0              NaN               NaN

[13889 rows x 509 columns]

## Add results for N2O

In [8]:
newcols = [c for c in n2o.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, n2o[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_FN2O_MISSING_TEST
++ FLAG_L2_FN2O_SSITC_TEST
++ FLAG_L2_FN2O_COMPLETENESS_TEST
++ FLAG_L2_FN2O_SCF_TEST
++ FLAG_L2_FN2O_N2O_VM97_SPIKE_HF_TEST
++ FLAG_L2_FN2O_N2O_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_FN2O_N2O_VM97_DROPOUT_TEST
++ SUM_L2_FN2O_HARDFLAGS
++ SUM_L2_FN2O_SOFTFLAGS
++ SUM_L2_FN2O_FLAGS
++ FLAG_L2_FN2O_QCF
++ FN2O_L2_QCF
++ FN2O_L2_QCF0
++ SN2O_SINGLE_gfRMED_L3.1
++ FLAG_SN2O_SINGLE_gfRMED_L3.1_ISFILLED
++ FN2O_L3.1
++ FN2O_L3.1_QCF
++ FN2O_L3.1_QCF0
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HAMPEL_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST
++ SUM_L3.2_FN2O_L3.1_HARDFLAGS
++ SUM_L3.2_FN2O_L3.1_SOFTFLAGS
++ SUM_L3.2_FN2O_L3.1_FLAGS
++ FLAG_L3.2_FN2O_L3.1_QCF
++ FN2O_L3.1_L3.2_QCF
++ FN2O_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SN2O_SINGLE_gfRMED_L3.1_ISFILLED  FN2O_L3.1  FN2O_L3.1_QCF  FN2O_L3.1_QCF0  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HAMPEL_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_FN2O_L3.1_HARDFLAGS  SUM_L3.2_FN2O_L3.1_SOFTFLAGS  SUM_L3.2_FN2O_L3.1_FLAGS  FLAG_L3.2_FN2O_L3.1_QCF  FN2O_L3.1_L3.2_QCF  FN2O_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    1.0  -0.065984            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            4.0                           0.0                       4.0                      2.0                 NaN                  NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   0.324973       0.324973        0.324973                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            0.324973             0.324973
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   0.053551       0.053551        0.053551                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            0.053551             0.053551
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   0.339963       0.339963        0.339963                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            0.339963             0.339963
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0  -0.983566      -0.983566       -0.983566                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0           -0.983566            -0.983566
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                    ...        ...            ...             ...                                          ...                                     ...                                          ...                                          ...                                                ...                            ...                           ...                       ...                      ...                 ...                  ...
2024-08-22 21:45:00  1014.14      1.14108  0.025231     1157.22         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   0.715026       0.715026             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0            0.715026                  NaN
2024-08-22 22:15:00  1014.10      1.14388  0.025170     1160.01         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   2.623038       2.623038             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0            2.623038                  NaN
2024-08-22 22:45:00  1014.08      1.14405  0.025167     1160.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   1.743544       1.743544             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0            1.743544                  NaN
2024-08-22 23:15:00  1014.01      1.14569  0.025132     1161.74         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   1.416209       1.416209             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0            1.416209                  NaN
2024-08-22 23:45:00  1014.01      1.14436  0.025161     1160.39         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   0.886456       0.886456             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0            0.886456                  NaN

[13889 rows x 538 columns]

## Add results for CH4

In [9]:
newcols = [c for c in ch4.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, ch4[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_FCH4_MISSING_TEST
++ FLAG_L2_FCH4_SSITC_TEST
++ FLAG_L2_FCH4_COMPLETENESS_TEST
++ FLAG_L2_FCH4_SCF_TEST
++ FLAG_L2_FCH4_CH4_VM97_SPIKE_HF_TEST
++ FLAG_L2_FCH4_CH4_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_FCH4_CH4_VM97_DROPOUT_TEST
++ SUM_L2_FCH4_HARDFLAGS
++ SUM_L2_FCH4_SOFTFLAGS
++ SUM_L2_FCH4_FLAGS
++ FLAG_L2_FCH4_QCF
++ FCH4_L2_QCF
++ FCH4_L2_QCF0
++ SCH4_SINGLE_gfRMED_L3.1
++ FLAG_SCH4_SINGLE_gfRMED_L3.1_ISFILLED
++ FCH4_L3.1
++ FCH4_L3.1_QCF
++ FCH4_L3.1_QCF0
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HAMPEL_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST
++ SUM_L3.2_FCH4_L3.1_HARDFLAGS
++ SUM_L3.2_FCH4_L3.1_SOFTFLAGS
++ SUM_L3.2_FCH4_L3.1_FLAGS
++ FLAG_L3.2_FCH4_L3.1_QCF
++ FCH4_L3.1_L3.2_QCF
++ FCH4_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SCH4_SINGLE_gfRMED_L3.1_ISFILLED  FCH4_L3.1  FCH4_L3.1_QCF  FCH4_L3.1_QCF0  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HAMPEL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_FCH4_L3.1_HARDFLAGS  SUM_L3.2_FCH4_L3.1_SOFTFLAGS  SUM_L3.2_FCH4_L3.1_FLAGS  FLAG_L3.2_FCH4_L3.1_QCF  FCH4_L3.1_L3.2_QCF  FCH4_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2023-11-07 15:45:00  1009.65      1.18057  0.024459     1191.96         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    1.0 -18.790539            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2023-11-07 16:15:00  1009.74      1.18107  0.024448     1192.57         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0  -4.360399      -4.360399             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           -4.360399                  NaN
2023-11-07 16:45:00  1009.93      1.18176  0.024430     1193.50         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   6.843150            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2023-11-07 17:15:00  1009.97      1.18428  0.024377     1196.09         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0   2.488800       2.488800        2.488800                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            2.488800             2.488800
2023-11-07 17:45:00  1010.06      1.18448  0.024372     1196.40         0.0                   1.0           0.5                               -4.5                                NaN                                NaN                               -4.5                             -3.0                              NaN                              NaN                             -3.0  ...                                    0.0  -9.177059      -9.177059       -9.177059                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0           -9.177059            -9.177059
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                    ...        ...            ...             ...                                          ...                                     ...                                          ...                                          ...                                                ...                            ...                           ...                       ...                      ...                 ...                  ...
2024-08-22 21:45:00  1014.14      1.14108  0.025231     1157.22         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0 -14.386380     -14.386380             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0          -14.386380                  NaN
2024-08-22 22:15:00  1014.10      1.14388  0.025170     1160.01         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  49.838100      49.838100             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           49.838100                  NaN
2024-08-22 22:45:00  1014.08      1.14405  0.025167     1160.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  14.259800            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2024-08-22 23:15:00  1014.01      1.14569  0.025132     1161.74         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  14.943390      14.943390             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           14.943390                  NaN
2024-08-22 23:45:00  1014.01      1.14436  0.025161     1160.39         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   5.248787            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN

[13889 rows x 567 columns]

# Export

## Export all data

In [10]:
filename = "46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4"
save_parquet(data=maindf, filename=filename)

Saved file 46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4.parquet (1.532 seconds).

'46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4.parquet'

## Export subset for REddyProc

In [11]:
from diive.core.times.times import insert_timestamp
export_REddyProc = maindf.copy()

In [12]:
newcols = [c for c in meteo.columns if c not in export_REddyProc]
export_REddyProc = pd.concat([export_REddyProc, meteo[newcols]], axis=1)

In [13]:
exportcols = ['NEE_L3.1_L3.2_QCF', 'LE_L3.1_L3.2_QCF', 'H_L3.1_L3.2_QCF',
              'USTAR',
              'sw_in', 'ta', 'vpd']
export_REddyProc = export_REddyProc[exportcols].copy()
locs = (export_REddyProc.index.year >= 2023) & (export_REddyProc.index.year <= 2025)
export_REddyProc = export_REddyProc[locs].copy()
export_REddyProc = insert_timestamp(data=export_REddyProc, convention="end", set_as_index=True)
export_REddyProc

                     NEE_L3.1_L3.2_QCF  LE_L3.1_L3.2_QCF  H_L3.1_L3.2_QCF     USTAR  sw_in         ta       vpd
TIMESTAMP_END
2023-10-17 00:30:00                NaN               NaN              NaN       NaN    0.0   1.966667  0.036616
2023-10-17 01:00:00                NaN               NaN              NaN       NaN    0.0   1.966667  0.034503
2023-10-17 01:30:00                NaN               NaN              NaN       NaN    0.0   1.566667  0.034438
2023-10-17 02:00:00                NaN               NaN              NaN       NaN    0.0   1.266667  0.037719
2023-10-17 02:30:00                NaN               NaN              NaN       NaN    0.0   1.400000  0.029746
...                                ...               ...              ...       ...    ...        ...       ...
2024-08-22 22:00:00                NaN               NaN              NaN  0.054183    0.0  15.870000  0.288649
2024-08-22 22:30:00                NaN               NaN              NaN  0.112660    0.0  15.160000  0.213907
2024-08-22 23:00:00                NaN               NaN              NaN  0.161695    0.0  15.100000  0.211994
2024-08-22 23:30:00                NaN               NaN              NaN  0.112738    0.0  14.683333  0.176924
2024-08-23 00:00:00                NaN               NaN              NaN  0.069966    0.0  14.993333  0.210485

[14928 rows x 7 columns]

In [14]:
filename = "46.2_FluxProcessingChain_L3.2_subset-forREddyProc"
export_REddyProc.to_csv(f"{filename}.csv", index=True)

</br>

---

# **End of notebook**

---

Congratulations, you reached the end of this notebook! Before you go let's store your finish time.

In [15]:
from datetime import datetime
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2026-09-17 15:47:20